package com.ipukr.elephant.security.rabc;

import lombok.*;

import java.io.Serializable;
import java.util.Date;

/**
* Created by Mybatis Generator on 2019/07/08
*/
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class Department implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Department.Id
     *
     * @mbg.generated Mon Jul 08 10:15:17 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Department.Dno
     *
     * @mbg.generated Mon Jul 08 10:15:17 CST 2019
     */
    private String dno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Department.Name
     *
     * @mbg.generated Mon Jul 08 10:15:17 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Department.Create_Time
     *
     * @mbg.generated Mon Jul 08 10:15:17 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Department.Create_Employee_Eno
     *
     * @mbg.generated Mon Jul 08 10:15:17 CST 2019
     */
    private String createEmployeeEno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Department.Last_Update_Time
     *
     * @mbg.generated Mon Jul 08 10:15:17 CST 2019
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Department.Last_Update_Employee_Eno
     *
     * @mbg.generated Mon Jul 08 10:15:17 CST 2019
     */
    private String lastUpdateEmployeeEno;
}