package com.ipukr.elephant.security.rabc;

import lombok.*;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
* Created by Mybatis Generator on 2019/07/08
*/
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class Employee extends UserAuthentification implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.Id
     *
     * @mbg.generated Mon Jul 08 10:15:16 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.Eno
     *
     * @mbg.generated Mon Jul 08 10:15:16 CST 2019
     */
    private String eno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.Name
     *
     * @mbg.generated Mon Jul 08 10:15:16 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.Gender
     *
     * @mbg.generated Mon Jul 08 10:15:16 CST 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.Mobile
     *
     * @mbg.generated Mon Jul 08 10:15:16 CST 2019
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.Password
     *
     * @mbg.generated Mon Jul 08 10:15:16 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.Email
     *
     * @mbg.generated Mon Jul 08 10:15:16 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.Portrait
     *
     * @mbg.generated Mon Jul 08 10:15:16 CST 2019
     */
    private String portrait;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.Organization_Id
     *
     * @mbg.generated Mon Jul 08 10:15:16 CST 2019
     */
    private Integer organizationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.Department_Id
     *
     * @mbg.generated Mon Jul 08 10:15:16 CST 2019
     */
    private Integer departmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.Post_Id
     *
     * @mbg.generated Mon Jul 08 10:15:16 CST 2019
     */
    private Integer postId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.Title
     *
     * @mbg.generated Mon Jul 08 10:15:16 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.Fix
     *
     * @mbg.generated Mon Jul 08 10:15:16 CST 2019
     */
    private Boolean fix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.Hiredate
     *
     * @mbg.generated Mon Jul 08 10:15:16 CST 2019
     */
    private Date hiredate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.Create_Time
     *
     * @mbg.generated Mon Jul 08 10:15:16 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.Create_Employee_Eno
     *
     * @mbg.generated Mon Jul 08 10:15:16 CST 2019
     */
    private String createEmployeeEno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.Last_Update_Time
     *
     * @mbg.generated Mon Jul 08 10:15:16 CST 2019
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.Last_Update_Employee_Eno
     *
     * @mbg.generated Mon Jul 08 10:15:16 CST 2019
     */
    private String lastUpdateEmployeeEno;

    private Boolean selected;

    private Department department;

    private Organization organization;

//    @Builder.Default
//    private List<Organization> subordinates = new ArrayList();
//
//    @Builder.Default
//    private List<Role> roles = new ArrayList();
//
//    @Builder.Default
//    private List<Permission> permissions = new ArrayList();

    @Override
    public String getKey() {
        return eno;
    }
}
