package com.ipukr.elephant.security.rabc;

import com.ipukr.elephant.security.Authority;
import lombok.*;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
* Created by Mybatis Generator on 2019/07/08
*/
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class Permission extends Authority implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Permission.Id
     *
     * @mbg.generated Mon Jul 08 10:15:17 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Permission.Resource
     *
     * @mbg.generated Mon Jul 08 10:15:17 CST 2019
     */
    private Integer resource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Permission.Name
     *
     * @mbg.generated Mon Jul 08 10:15:17 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Permission.Remark
     *
     * @mbg.generated Mon Jul 08 10:15:17 CST 2019
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Permission.Icon
     *
     * @mbg.generated Mon Jul 08 10:15:17 CST 2019
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Permission.Url_Template
     *
     * @mbg.generated Mon Jul 08 10:15:17 CST 2019
     */
    private String urlTemplate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Permission.Method
     *
     * @mbg.generated Mon Jul 08 10:15:17 CST 2019
     */
    private String method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Permission.Path
     *
     * @mbg.generated Mon Jul 08 10:15:17 CST 2019
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Permission.Level
     *
     * @mbg.generated Mon Jul 08 10:15:17 CST 2019
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Permission.Parent
     *
     * @mbg.generated Mon Jul 08 10:15:17 CST 2019
     */
    private Integer parent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Permission.Sort
     *
     * @mbg.generated Mon Jul 08 10:15:17 CST 2019
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Permission.Status
     *
     * @mbg.generated Mon Jul 08 10:15:17 CST 2019
     */
    private Boolean status;

    private Boolean selected;

    private List<Permission> children = new ArrayList();


    /**
     * 递归辅助属性，用于找出根结点
     */
    @Builder.Default
    private Boolean leaf = false;

	@Override
	public boolean match(String key, String... args) {
		boolean bool = true;
		bool = bool && path!=null && path.equals(key);
		if (args.length == 0) {
			bool = bool && method!=null && method.toUpperCase().equals(args[0].toUpperCase());
		}
		return bool;
	}

	@Override
	public boolean match(Authority authority) {
		if (authority instanceof Permission) {
			Permission permission = (Permission) authority;
			boolean bool = true;
			bool = bool && path!=null && path.equals(permission.getPath());
			return bool;
		} else {
			return false;
		}
	}
}