package com.blackdotan.elephant.utils.domain;

import lombok.*;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ToString
public class Organization implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Organization.Id
     *
     * @mbg.generated Mon Jul 08 10:15:16 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Organization.Ono
     *
     * @mbg.generated Mon Jul 08 10:15:16 CST 2019
     */
    private String ono;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Organization.Type
     *
     * @mbg.generated Mon Jul 08 10:15:16 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Organization.Name
     *
     * @mbg.generated Mon Jul 08 10:15:16 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Organization.Address
     *
     * @mbg.generated Mon Jul 08 10:15:16 CST 2019
     */
    private String address;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Organization.Superior_Id
     *
     * @mbg.generated Mon Jul 08 10:15:16 CST 2019
     */
    private Integer superiorId;

    private Boolean selected;

    private List<Organization> children = new ArrayList();

    public void setSelected(Boolean selected) {
        this.selected = selected;
    }

    public Boolean getSelected() {
        return this.selected;
    }

    public void setChildren(List<Organization> children) {
        this.children = children;
    }

    public List<Organization> getChildren() {
        return this.children;
    }
}

