package com.blackdotan.elephant.security.rabc;

import lombok.*;

import java.io.Serializable;
import java.util.Date;

/**
* Created by Mybatis Generator on 2019/07/08
*/
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class Role extends RoleAuthentification implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Role.Id
     *
     * @mbg.generated Mon Jul 08 10:15:16 CST 2019
     */
    private Integer id;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Role.Name
     *
     * @mbg.generated Mon Jul 08 10:15:17 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Role.Remark
     *
     * @mbg.generated Mon Jul 08 10:15:17 CST 2019
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Role.Fix
     *
     * @mbg.generated Mon Jul 08 10:15:17 CST 2019
     */
    private Boolean fix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Role.Group_Id
     *
     * @mbg.generated Mon Jul 08 10:15:17 CST 2019
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Role.Create_Time
     *
     * @mbg.generated Mon Jul 08 10:15:17 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Role.Create_Employee_Eno
     *
     * @mbg.generated Mon Jul 08 10:15:17 CST 2019
     */
    private String createEmployeeEno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Role.Last_Update_Time
     *
     * @mbg.generated Mon Jul 08 10:15:17 CST 2019
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Role.Last_Update_Employee_Eno
     *
     * @mbg.generated Mon Jul 08 10:15:17 CST 2019
     */
    private String lastUpdateEmployeeEno;

    @Override
    public String getKey() {
        return name;
    }

//    private Group group;
//
//    private List<Permission> permissions = new ArrayList();
//
//    public void setGroup(Group group) {
//        this.group = group;
//    }
//
//    public Group getGroup() {
//        return this.group;
//    }
//
//    public void setPermissions(List<Permission> permissions) {
//        this.permissions = permissions;
//    }
//
//    public List<Permission> getPermissions() {
//        return this.permissions;
//    }
}
