package com.ipukr.elephant.common.template;

import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Created by ryan on 上午1:56.
 * @param <T> Entity对象(eg: User, Book)
 * @param <K> 主键数据类型(eg: Integer, String)
 */
public interface AbstractMapper<T, K extends java.io.Serializable> {
    /**
     * 根据主键列表删除
     *
     * @param records
     * @return
     */
    int deleteByIds(@Param("records") List records);

    /**
     * 匹配判断
     *
     * @param record
     * @return
     */
    boolean exist(@Param("record") T record);

    /**
     * 判断主键是否存在
     * @param record
     * @return
     */
    boolean existPrimaryKey(@Param("id") K record);

    /**
     * 根据主键删除数据
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_comment
     *
     * @mbggenerated Sun Jan 08 19:33:20 CST 2017
     */
    int deleteByPrimaryKey(K id);

    /**
     * 插入数据
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_comment
     *
     * @mbggenerated Sun Jan 08 19:33:20 CST 2017
     */
    int insert(T record);

    /**
     * 动态插入数据
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_comment
     *
     * @param record 待处理对象
     * @return
     */
    int insertSelective(T record);

    /**
     * 动态插入数据 / 索引冲突更新
     *
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_comment
     *
     * @param record 待处理对象
     * @return
     */
    int insertSelectiveIgnore(@Param("record") T record);

    /**
     * 获取所有数据
     * @return
     */
    List<T> findAll();


    /**
     * 分页获取所有数据
     * @param bounds
     * @return
     */
    List<T> findAll(PageBounds bounds);
    /**
     * 分页获取数据
     * @param bounds
     * @return
     */
    @Deprecated
    List<T> find(PageBounds bounds);

    /**
     * 根据主键列表获取数据
     * @param ids
     * @return
     */
    List<T> findByIds(@Param("ids") List ids);

    /**
     * 分页根据主键列表获取数据
     * @param ids
     * @param bounds
     * @return
     */
    List<T> findByIds(@Param("ids") List ids, PageBounds bounds);

    /**
     * 匹配查询
     * @param record
     * @return
     */
    List<T> query(@Param("record") T record);

    /**
     * 分页, 匹配查询
     * @param record
     * @param bounds
     * @return
     */
    List<T> query(@Param("record") T record, PageBounds bounds);


    /**
     * 模糊查询
     * @param record
     * @return
     */
    List<T> search(@Param("record") T record);

    /**
     * 分页, 模糊查询
     * @param record
     * @param bounds
     * @return
     */
    List<T> search(@Param("record") T record, PageBounds bounds);

    /**
     * 匹配, 统计记录数
     * @param record
     * @return
     */
    Integer count(@Param("record") T record);

    /**
     * 执行SQL语句
     * @param sql
     * @return
     */
    List<Map> sql(@Param("sql") String sql);

    /**
     * 根据主键获取记录
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_comment
     *
     * @mbggenerated Sun Jan 08 19:33:20 CST 2017
     */
    T selectByPrimaryKey(K id);

    /**
     * 根据主键, 动态更新记录
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_comment
     *
     * @mbggenerated Sun Jan 08 19:33:20 CST 2017
     */
    int updateByPrimaryKeySelective(T record);

    /**
     * 根据主键, 更新记录
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_comment
     *
     * @mbggenerated Sun Jan 08 19:33:20 CST 2017
     */
    int updateByPrimaryKey(T record);

    /**
     * 根据条件, 获取记录
     * @param condition
     * @return
     */
    List<T> condition(@Param("condition") String condition);

    /**
     * 分页, 根据条件, 获取记录
     * @param condition
     * @param bounds
     * @return
     */
    List<T> condition(@Param("condition") String condition, PageBounds bounds);

    /**
     * 数据抽样, <br>
     *
     * <p>随机获取一条记录</p>
     *
     * @return
     */
    T example();

    /**
     * 数据接口抽样 <br>
     *
     * @param n 返回记录数
     * @return
     */
    List<T> nexample(int n);
}
